#if defined _vip_base_included
#endinput
#endif
#define _vip_base_included

/*
VIP JB PACK 1
+2 x bani daca echipa ta castiga
+la /lr nu plateste jocurile, freegun
+150 hp la inceput de runda
+cumperi arme din gunshop fara sa platesti
+voce oricand
+slot
+acces la modele
+acces la paint
+acces la ejaculate
+sa te bagi ct cand vrei
-flash light colorat
-fireworks

VIP JB PACK 2 (in desfasurare)
La fiecare runda primesti garantat cate 6k (6000$) daca nu ai devenit rebel (la CT daca nu ai murit)
Ai 1 din 10 şanse să primeşti un deagle cu 7 gloante la fiecare runda
2x bani daca raspunzi corect la o intrebare de trivia (chiar daca joaca trivia cand e mort)
+150 hp la inceput de runda
voce oricand
slot
acces la modele
acces la paint
acces la ejaculate
sa te bagi ct cand vrei

VIP JB PACK 3 (in desfasurare)
Nu ai limita de cumparare la shop-ul de la prizonieri
Regenerarea la /dorm creste cu x2
armură instant la T
+150 hp la inceput de runda
voce oricand
slot
acces la modele
acces la paint
acces la ejaculate
sa te bagi ct cand vrei

*/

native get_vip_type(id);// returns type of the vip
